#define ZR_VER_PRODUCT_NAME	    "Zombie:Reloaded"
#define ZR_VER_COPYRIGHT        "Copyright (C) 2009-2025  Greyscale, Richard Helgeby, maxime1907, BotoX, zaCade, .Rushaway, Franug, Anubis"
#define ZR_VER_VERSION          VERSION
#define ZR_VER_BRANCH           "master"
#define ZR_VER_REVISION         "0"
#define ZR_VER_LICENSE          "GNU GPL, Version 3"
#define ZR_VER_DATE             "Wed Jan 23 09:38:56 CEST 2025"
