name: ZombieReloaded_Wiki
description: A wiki to explain all cvars related to ZombieReloaded
homepage: https://srcdslab.github.io/sm-plugin-zombiereloaded/
author: SRCDSLAB <https://discord.gg/EFbtjSUUxG>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  pwa: ^0.2.0
  collection: ^1.14.12
  quiver: ^2.1.2+1
  csv: ^4.0.3
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.7.3
  build_web_compilers: ^2.9.0
  effective_dart: ^1.1.0